spring:
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rentAcar
    username: postgres
    password: 123456
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.postgresql
